### ISSUE TITLE
Create Lambda error because of nodejs6.10

### ISSUE THREAD

**Issue by Scentyoo** [martindsouza/docker-amazon-ask-cli#3]
I just tried to use this audio example: https://github.com/alexa/skill-sample-nodejs-audio-player/tree/mainline/multiple-streams

But it fails with the following error:

> Create Lambda error.
InvalidParameterValueException: The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.

Is this a configuration problem? Or am I missing something? Or is the "node:9.7.1-alpine" Docker image the problem?

**Comment by martindsouza** [comment]
@Scentyoo I'm not actively using this docker image anymore. That said I did update the base image to use the current version of `node:current-alpine`. Can you please retest? You'll need to do a `docker pull martindsouza/amazon-ask-cli`

**Comment by Scentyoo** [comment]
Great, thank you very much! This works!

I tried to change this myself, but I did not find a way to use the Dockerfile locally. I tried the commands, but I failed with the following errors:
```
docker build -t ask-cli-demo .
docker run -it --rm `
    -v C:\path\to\ask-config:/home/node/.ask `
    -v C:\path\to\aws-config:/home/node/.aws `
    -v C:\path\to\app:/home/node/app `
    ask-cli-demo `
    ask new --skill-name HelloWorld
? Please select the runtime Node.js v10
? List of templates you can choose Hello World
Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```
Do you have an idea why this doesn't work?

**Comment by martindsouza** [comment]
@Scentyoo your welcome, glad it worked. I'm not sure why your build didn't work. Did the build end with a success message? I'm also not sure if it's a Windows issue. 

I'll close this issue to mark the original issue has been resolved but we can keep this discussion going regarding your custom build and run.

**Comment by Scentyoo** [comment]
This was the message:
```
Successfully built 18138d395b91
Successfully tagged ask-cli-demo:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
```
Do you think this might be the problem?

**Comment by martindsouza** [comment]
@Scentyoo did you do a `git pull` on this project so you have the latest files?
